---
title: "FinalProject"
author: "Mirella Hernandez"
date: "April 27, 2017"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
install.packages("macleish")
```

```{r}
install.packages("sp")
library(sp)

```


```{r}
names(macleish_layers)
```

```{r}
macleish_layers[["landmarks"]] %>%
  summary()
```






```{r}
install.packages("leaflet")
library(leaflet)
```



```{r}
install.packages("rgeos")
```

```{r}
library(rgeos)
```


#THIS
```{r}

proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=42.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
parking <- data.frame(lat = 42.448013, lon = -72.680663)%>%
     spTransform(CRS(proj4_aea))



parking_buffed <- streams_aea %>%
  gBuffer(width = 10) %>%
  spTransform(CRS("+init=epsg:4326"))



```




#THIS
```{r}
group_campsite <- data.frame(lat = 42.450976, lon = -72.678154)
remote_campsite <- data.frame(lat = 42.458570, lon =  -72.674732)


leaflet() %>%
  addTiles() %>%
  
  ##
#  addProviderTiles("Esri.WorldTopoMap", group = "Topography") %>%
  
  addMarkers(lng = ~lon, lat = ~lat, data = group_campsite,
             popup = "Group Campsite") %>%
  addMarkers(lng = ~lon, lat = ~lat, data = remote_campsite,
             popup = "Remote Campsite") %>%

  addPolylines(data = macleish_layers[["trails"]],
              color = "brown", popup = "trails") %>%
  addPolylines(data = macleish_layers[["streams"]],
               popup = "streams") %>%
  addPolylines(data = macleish_layers[["forests"]],
               color = "green", popup = "forests") %>%
  addMarkers(lng = ~lon, lat = ~lat, data = parking,
              popup = "Parking") %>%

  #addCircles(lng = ~lon, lat = ~lat, data = parking,
             #radius = 804.672, popup = "Parking Away")
  addPolylines(data = parking_buffed, weight = 2, popup = "Parking Away")
  
  
```


```{r}
url <- "http://wsgw.mass.gov/data/gispub/shape/state/contours250k.zip"
download.file(url, destfile = basename(url))
unzip("contours250k.zip", exdir = "contours")
```

```{r}
library(rgdal)
dsn <- path.expand("Contours")
dsn
list.files(dsn)

```


```{r}
ogrListLayers(dsn)
```



```{r}

ogrInfo(dsn, layer = "CONTOURS250K_ARC")
```

```{r}
contours <- readOGR(dsn, "CONTOURS250K_ARC")
summary(contours)
```

```{r}
plot(contours)
```

1.add tiles (provider tile)*****
add macleish layer (contours)
web: world something 
group toppgraphy



```{r}
proj4string(contours)
```

